project_id = "smwjzloqamtvemljedkv"

[functions.track-email-open]
verify_jwt = false

[functions.track-email-click]
verify_jwt = false

[functions.monitor-campaigns]
verify_jwt = false

[functions.sync-mailbox]
verify_jwt = false

[functions.check-email-replies]
verify_jwt = false

[functions.book-demo]
verify_jwt = false

[functions.automation-runner]
verify_jwt = false

[functions.automation-webhook]
verify_jwt = false

[db]
major_version = 15

